USE UNI;

DELETE FROM PROFESSOR_POSITION;
GO

DELETE FROM PROFESSOR;
GO

SET IDENTITY_INSERT PROFESSOR_POSITION ON;
GO

-- insert DATA to  PROFESSOR_POSITION table
INSERT INTO PROFESSOR_POSITION (ID, NAME)
VALUES
(1, 'PROFESSOR'),
(2, 'ASSISTANT PROFESSOR'),
(3, 'LECTURER'),
(4, 'ASSISTANT LECTURER'),
(5, 'RESEARCHER');
GO

SET IDENTITY_INSERT PROFESSOR_POSITION OFF;
GO

SET IDENTITY_INSERT PROFESSOR ON;
GO

-- insert DATA to  PROFESSOR table
INSERT INTO  PROFESSOR  (ID, FIRSTNAME, LASTNAME,POSITION_ID)
VALUES
(1, 'MAHMOD', 'MAHMOD', 1),
(2, 'ELHAM', 'MAHMAD', 1),
(3, 'MAHMAD', 'ABDULHAMED', 1),
(4, 'MAROA', 'ABDULGHAFAR', 2),
(5, 'ESSAM', 'AMIN', 1),
(6, 'SALWA', 'SAMY', 2),
(7, 'AHMED', 'FOUAD', 1),
(8, 'KAREEM', 'RASHAD', 4),
(9,  'YASMINE', 'YUSEF', 2),
(10, 'ABDULTAWAB', 'AHMED', 3),
(11, 'ABDULHADY', 'NABEH', 1),
(12, 'SOUHYLA', 'ELGUAR', 3);
GO

SET IDENTITY_INSERT PROFESSOR OFF;
GO
